// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElRow: typeof import('element-plus/es')['ElRow']
    Header: typeof import('./src/components/Header.vue')['default']
    'Header copy': typeof import('./src/components/Header copy.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    'Sidebar copy': typeof import('./src/components/Sidebar copy.vue')['default']
    Tags: typeof import('./src/components/Tags.vue')['default']
    'Tags copy': typeof import('./src/components/Tags copy.vue')['default']
  }
}

export {}
